defaults:
  - _self_
  - data: cifar10.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: timm.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???